"use client";
import { useState } from "react";
import {
  ArrowDownRight, ArrowUpRight, Check, ChevronRight, Code2, ExternalLink,
  Github, Globe2, Layers3, Linkedin, Mail, Menu, MessageCircle, MonitorSmartphone, Phone,
  Server, ShoppingBag, Sparkles, X, Zap,
} from "lucide-react";

const skills = [
  { name: "HTML", type: "Frontend", icon: "</>" }, { name: "CSS", type: "Frontend", icon: "#" },
  { name: "JavaScript", type: "Frontend", icon: "JS" }, { name: "React", type: "Frontend", icon: "R" },
  { name: "Next.js", type: "Frontend", icon: "N" }, { name: "TypeScript", type: "Frontend", icon: "TS" },
  { name: "Tailwind CSS", type: "Frontend", icon: "TW" }, { name: "Node.js", type: "Backend", icon: "N" },
  { name: "REST APIs", type: "Backend", icon: "API" }, { name: "MongoDB", type: "Database", icon: "M" },
  { name: "Git", type: "Tools & Services", icon: "git" }, { name: "GitHub", type: "Tools & Services", icon: "GH" },
  { name: "Cloudinary", type: "Tools & Services", icon: "C" },
];

const services = [
  ["Website Development", "Modern, responsive websites built around your business needs.", Globe2, "/mazhai-boutique/homepage.png"],
  ["Full Stack Web Development", "Complete web applications with frontend, backend and database integration.", Layers3, "/mazhai-boutique/project-cover.svg"],
  ["E-commerce Development", "Online stores with thoughtful product browsing and shopping functionality.", ShoppingBag, "/mazhai-boutique/collections.png"],
  ["React & Next.js Development", "Fast, scalable applications built with modern React architecture.", Code2, "/mazhai-boutique/saree-editorial.svg"],
  ["Responsive Web Design", "Interfaces that work smoothly across mobile, tablet and desktop.", MonitorSmartphone, "/mazhai-boutique/homepage.png"],
  ["Website Maintenance", "Bug fixes, improvements, updates and ongoing website support.", Zap, "/mazhai-boutique/project-cover.svg"],
  ["API Integration", "Connect applications with APIs and external services.", Server, "/mazhai-boutique/collections.png"],
  ["Performance Optimization", "Improve speed, responsiveness and the overall user experience.", Sparkles, "/mazhai-boutique/saree-editorial.svg"],
];

const approach = ["Responsive and mobile-first development", "Clean and maintainable code", "Modern technologies", "Performance-focused development", "User-friendly interfaces", "Attention to detail", "Custom solutions", "Clear communication", "Reliable project delivery"];
const gallery = ["Homepage", "Product listing", "Product details", "Shopping cart", "Mobile responsive view"];
const mazhaiImageUrl = "/mazhai-boutique/saree-editorial.svg";
const mazhaiCollectionsUrl = "/mazhai-boutique/saree-editorial.svg";
const aiFeatures = ["AI shopping assistant for product questions", "Natural-language saree and occasion discovery", "Personalized recommendations based on preferences", "Smart style guidance and size assistance"];
const educationProjects = [
  ["Medication Reminder System", "A user-focused reminder application for prescribed medication schedules, with database-driven notifications, customizable reminders, intuitive UI, error handling and secure patient data storage."],
  ["Logic Card Game", "A real-time multiplayer card game supporting more than five players, with synchronized gameplay, private card handling, turn-based rules, victory conditions, scoring and a Boost feature."],
  ["File Transfer Protocol", "A project implementing FTP to move files between a client and server, providing an easy way to access and manage files without cables or additional software."],
];
const education = [
  ["B.Tech - Artificial Intelligence and Data Science", "K. Ramakrishnan College of Engineering", "2025 / 2028"],
  ["Diploma in Computer Engineering", "Dhanalakshmi Srinivasan Polytechnic College", "2022 / 2025"],
  ["10th", "Sri Vivekananda Matriculation School", "2018 / 2019"],
];

function PlaceholderVisual({ label = "Project preview", compact = false }: { label?: string; compact?: boolean }) {
  return <div className={`relative overflow-hidden rounded-[2px] border border-ink/10 bg-[#dce9df] ${compact ? "h-52" : "min-h-[350px]"}`}>
    <div className="absolute -right-10 -top-12 h-48 w-48 rounded-full border-[28px] border-coral/30" />
    <div className="absolute bottom-[-70px] left-[-20px] h-56 w-56 rounded-full bg-[#f4c9a5]/60" />
    <div className={`absolute left-[9%] top-[14%] w-[82%] overflow-hidden rounded-sm border border-ink/10 shadow-2xl shadow-ink/10 ${compact ? "bg-paper" : "bg-paper/90"}`}>
      {!compact ? <img src={mazhaiImageUrl} alt="Mazhai Boutique home page" className="h-64 w-full object-cover sm:h-80" /> : <><div className="flex h-7 items-center gap-1.5 border-b border-ink/10 px-3"><i className="h-1.5 w-1.5 rounded-full bg-coral" /><i className="h-1.5 w-1.5 rounded-full bg-ink/20" /><i className="h-1.5 w-1.5 rounded-full bg-ink/20" /><span className="ml-auto h-2 w-16 rounded-full bg-ink/10" /></div><div className="grid grid-cols-[1.1fr_.9fr] gap-3 p-4"><div><div className="mb-3 h-2 w-16 rounded bg-coral" /><div className="h-7 w-4/5 bg-ink/90" /><div className="mt-1 h-7 w-3/5 bg-ink/90" /><div className="mt-4 h-5 w-20 rounded-full bg-ink" /></div><div className="h-36 rounded-sm bg-[#c7d9c8]" /></div><div className="grid grid-cols-3 gap-2 px-4 pb-4"><div className="h-12 bg-[#ead5bd]" /><div className="h-12 bg-[#b9d0c6]" /><div className="h-12 bg-[#edb99f]" /></div></>}
    </div>
    <span className="absolute bottom-4 left-5 font-mono text-[10px] uppercase tracking-[.2em] text-ink/55">{label}</span>
  </div>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [lightbox, setLightbox] = useState<string | null>(null);
    const nav = [["About", "about"], ["Education", "education"], ["Services", "services"], ["Skills", "skills"], ["Projects", "projects"], ["Contact", "contact"]];
  return <main>
    <header className="fixed left-0 right-0 top-0 z-40 border-b border-ink/10 bg-paper/90 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
      <a href="#top" className="font-display text-lg font-bold tracking-tight">VJ<span className="text-coral">.</span></a>
      <nav className="hidden items-center gap-7 text-xs font-bold uppercase tracking-[.14em] text-ink/65 md:flex">{nav.map(([label, id]) => <a className="transition-colors hover:text-coral" key={id} href={`#${id}`}>{label}</a>)}</nav>
      <a href="#contact" className="hidden items-center gap-2 rounded-full bg-ink px-4 py-2.5 text-xs font-bold uppercase tracking-widest text-paper transition-transform hover:-translate-y-0.5 md:flex">Start a project <ArrowUpRight size={14} /></a>
      <button aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)} className="rounded-full border border-ink/15 p-2 md:hidden">{menuOpen ? <X size={19} /> : <Menu size={19} />}</button>
    </div>{menuOpen && <nav className="border-t border-ink/10 bg-paper px-5 py-5 md:hidden">{nav.map(([label, id]) => <a onClick={() => setMenuOpen(false)} className="block border-b border-ink/10 py-3 text-sm font-bold uppercase tracking-wider" key={id} href={`#${id}`}>{label}</a>)}</nav>}</header>

    <section id="top" className="grid-paper overflow-hidden px-5 pb-20 pt-32 lg:px-8 lg:pb-28 lg:pt-44"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.08fr_.92fr]">
      <div className="reveal"><p className="mb-6 flex items-center gap-3 font-mono text-xs uppercase tracking-[.22em] text-coral"><span className="h-px w-8 bg-coral" /> Available for freelance projects</p><h1 className="max-w-3xl font-display text-[clamp(3.2rem,8vw,7rem)] font-medium leading-[.91] tracking-[-.06em]">Building digital<br /><span className="text-coral">with intent.</span></h1><p className="mt-8 max-w-xl text-base leading-7 text-ink/65 md:text-lg">I am Visvaeswaraiya Jayakumar, a Full Stack Web Developer building modern, responsive and high-performance web experiences.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#projects" className="group flex items-center gap-3 rounded-full bg-coral px-5 py-3.5 text-sm font-bold text-white transition-transform hover:-translate-y-1">View my work <ArrowDownRight size={17} className="transition-transform group-hover:rotate-[-45deg]" /></a><a href="#contact" className="flex items-center gap-3 rounded-full border border-ink/20 px-5 py-3.5 text-sm font-bold transition-colors hover:border-ink hover:bg-white/50">Let's work together <ArrowUpRight size={17} /></a></div><div className="mt-14 flex items-center gap-5 text-ink/55"><span className="font-mono text-[10px] uppercase tracking-widest">Find me online</span><a href="#contact" aria-label="GitHub placeholder" className="transition-colors hover:text-coral"><Github size={18} /></a><a href="#contact" aria-label="LinkedIn placeholder" className="transition-colors hover:text-coral"><Linkedin size={18} /></a><a href="#contact" aria-label="Fiverr placeholder" className="font-bold transition-colors hover:text-coral">fi.</a></div></div>
      <div className="reveal delay-2 relative mx-auto w-full max-w-[520px]"><div className="absolute -left-4 top-8 h-16 w-16 border-l border-t border-coral" /><div className="absolute -bottom-4 right-0 h-24 w-24 rounded-full border border-ink/20" /><div className="relative rotate-2 bg-ink p-3 shadow-2xl shadow-ink/20"><div className="flex items-center justify-between border-b border-white/15 px-3 py-3 text-[10px] font-mono uppercase tracking-widest text-paper/50"><span>Selected work / 01</span><span>Full stack</span></div><div className="p-3"><PlaceholderVisual label="Mazhai Boutique / editable preview" /></div></div><div className="absolute -bottom-7 -left-4 rotate-[-8deg] bg-[#f4c9a5] px-4 py-3 font-mono text-[10px] font-bold uppercase tracking-widest">Design + build</div></div>
    </div></section>

    <section id="about" className="border-t border-ink/10 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.45fr_1fr]"><div><p className="section-label">01 / About</p><h2 className="mt-4 font-display text-4xl tracking-[-.04em] md:text-5xl">Ideas into<br />useful things.</h2></div><div className="max-w-3xl"><p className="text-2xl leading-tight tracking-[-.03em] md:text-4xl">I am a Full Stack Web Developer focused on building modern, responsive and user-friendly websites and web applications.</p><p className="mt-7 max-w-xl leading-7 text-ink/60">I enjoy turning ideas into practical digital experiences using modern web technologies, with a strong focus on clean interfaces, performance and usability.</p><div className="mt-10 grid grid-cols-2 gap-6 border-t border-ink/10 pt-6 text-sm text-ink/60 md:grid-cols-3"><div><strong className="block font-display text-2xl text-ink">01</strong>Featured project</div><div><strong className="block font-display text-2xl text-ink">13</strong>Core technologies</div><div><strong className="block font-display text-2xl text-ink">IN</strong>Based in India</div></div></div></div></section>

    <section id="education" className="border-t border-ink/10 bg-[#ead5bd]/35 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.45fr_1fr]"><div><p className="section-label">02 / Education</p><h2 className="mt-4 font-display text-4xl tracking-[-.04em] md:text-5xl">Curious,<br />adaptable,<br />building forward.</h2></div><div><p className="max-w-2xl text-xl leading-8 text-ink/75">Seeking innovative and challenging opportunities in a growing organization where I can use my skills and knowledge while continuing to grow.</p><div className="mt-12 border-t border-ink/15 pt-6"><p className="section-label">Education</p><div className="mt-5 grid gap-0">{education.map(([degree, school, years]) => <div className="grid gap-2 border-b border-ink/15 py-5 md:grid-cols-[1fr_auto]" key={degree}><div><h3 className="font-display text-xl">{degree}</h3><p className="mt-1 text-sm text-ink/60">{school}</p></div><span className="font-mono text-xs text-coral">{years}</span></div>)}</div></div><div className="mt-12 border-t border-ink/15 pt-6"><p className="section-label">Strengths</p><div className="mt-5 flex flex-wrap gap-3">{["Good communication", "Quick learner", "Easily adaptable"].map((item) => <span className="rounded-full border border-ink/20 px-4 py-2 text-sm" key={item}>{item}</span>)}</div></div></div></div></div></section>

    <section className="border-t border-ink/10 px-5 py-16 lg:px-8"><div className="mx-auto max-w-7xl"><p className="section-label">College-level projects</p><h3 className="mt-3 font-display text-3xl tracking-[-.04em]">Academic builds, thoughtfully made.</h3><div className="mt-8 grid gap-5 lg:grid-cols-3">{educationProjects.map(([title, description], index) => <article className="border border-ink/15 bg-white/35 p-5" key={title}><span className="font-mono text-xs text-coral">0{index + 2}</span><h4 className="mt-8 font-display text-2xl">{title}</h4><p className="mt-4 text-sm leading-6 text-ink/60">{description}</p></article>)}</div></div></section>

    <section id="services" className="border-y border-ink/10 bg-[#ead5bd]/45 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><p className="section-label">02 / Services</p><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="font-display text-4xl tracking-[-.04em] md:text-6xl">Good work starts<br />with <span className="text-coral">clarity.</span></h2><p className="max-w-xs text-sm leading-6 text-ink/60">Focused development support for ideas that deserve a thoughtful digital home.</p></div><div className="mt-12 grid border-l border-t border-ink/15 md:grid-cols-2 lg:grid-cols-4">{services.map(([title, desc, Icon]) => { const ServiceIcon = Icon as typeof Globe2; return <div className="group border-b border-r border-ink/15 p-5 transition-colors hover:bg-paper" key={title as string}><ServiceIcon size={20} className="text-coral" /><h3 className="mt-10 font-display text-xl">{title as string}</h3><p className="mt-3 text-sm leading-6 text-ink/60">{desc as string}</p><ChevronRight size={17} className="mt-8 text-ink/35 transition-transform group-hover:translate-x-1" /></div> })}</div></div></section>

    <section id="skills" className="bg-ink px-5 py-20 text-paper lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="section-label text-coral">03 / Toolkit</p><h2 className="mt-4 font-display text-4xl tracking-[-.04em] md:text-5xl">Built on a solid<br />technical foundation.</h2></div><p className="max-w-xs text-sm leading-6 text-paper/55">The tools I use to shape clear, reliable and maintainable web experiences.</p></div><div className="mt-12 grid grid-cols-2 border-l border-t border-paper/15 sm:grid-cols-3 lg:grid-cols-5">{skills.map((skill) => <div key={skill.name} className="group border-b border-r border-paper/15 p-4 transition-colors hover:bg-paper hover:text-ink md:p-5"><span className="font-mono text-[11px] text-coral">{skill.icon}</span><h3 className="mt-8 text-sm font-bold">{skill.name}</h3><p className="mt-1 text-[10px] uppercase tracking-widest text-paper/40 group-hover:text-ink/50">{skill.type}</p></div>)}</div></div></section>

    <section id="projects" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><p className="section-label">04 / Selected work</p><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="font-display text-4xl tracking-[-.04em] md:text-6xl">One project,<br /><span className="text-coral">carefully made.</span></h2><p className="max-w-sm text-sm leading-6 text-ink/60">A closer look at a full stack e-commerce experience. More work will be added here over time.</p></div><div className="mt-12 grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><button onClick={() => setLightbox("Mazhai Boutique") } className="text-left"><PlaceholderVisual label="Click to open gallery" /></button><div className="flex flex-col justify-between border-t border-ink/15 pt-5 lg:border-l lg:border-t-0 lg:pl-8"><div><div className="flex items-center justify-between text-[10px] font-mono uppercase tracking-widest text-ink/50"><span>E-commerce website</span><span>01 / 01</span></div><h3 className="mt-10 font-display text-4xl tracking-[-.04em]">Mazhai Boutique</h3><p className="mt-5 leading-7 text-ink/65">Designed and developed a modern, responsive e-commerce website focused on a smooth browsing and shopping experience across desktop and mobile devices.</p><div className="mt-7 flex flex-wrap gap-2">{["Next.js", "React", "TypeScript", "Tailwind CSS", "Node.js", "MongoDB", "Cloudinary"].map((item) => <span className="rounded-full border border-ink/15 px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider" key={item}>{item}</span>)}</div></div><div className="mt-10 border-t border-ink/10 pt-6"><p className="mb-4 font-mono text-[10px] uppercase tracking-widest text-ink/45">Implemented features</p><div className="grid grid-cols-2 gap-y-3 text-sm text-ink/65">{["Responsive design", "Product browsing", "Product details", "Shopping cart", "Image management", "API integration"].map(item => <span className="flex items-center gap-2" key={item}><Check size={14} className="text-coral" />{item}</span>)}</div><div className="mt-8 flex flex-wrap gap-4"><a href="#contact" className="flex items-center gap-2 text-sm font-bold text-coral">Live demo <ExternalLink size={15} /></a><a href="#contact" className="flex items-center gap-2 text-sm font-bold">View project <ArrowUpRight size={15} /></a></div></div></div></div>
      
    </div></section>

    <section id="services" className="border-y border-ink/10 bg-[#ead5bd]/45 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><p className="section-label">02 / Services</p><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="font-display text-4xl tracking-[-.04em] md:text-6xl">Good work starts<br />with <span className="text-coral">clarity.</span></h2><p className="max-w-xs text-sm leading-6 text-ink/60">Focused development support for ideas that deserve a thoughtful digital home.</p></div><div className="mt-12 grid border-l border-t border-ink/15 md:grid-cols-2 lg:grid-cols-4">{services.map(([title, desc, Icon]) => { const ServiceIcon = Icon as typeof Globe2; return <div className="group border-b border-r border-ink/15 p-5 transition-colors hover:bg-paper" key={title as string}><ServiceIcon size={20} className="text-coral" /><h3 className="mt-10 font-display text-xl">{title as string}</h3><p className="mt-3 text-sm leading-6 text-ink/60">{desc as string}</p><ChevronRight size={17} className="mt-8 text-ink/35 transition-transform group-hover:translate-x-1" /></div> })}</div></div></section>

    <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.45fr_1fr]"><div><p className="section-label">05 / Approach</p><h2 className="mt-4 font-display text-4xl tracking-[-.04em] md:text-5xl">Thoughtful by<br />default.</h2></div><div className="grid gap-0 border-t border-ink/15 sm:grid-cols-2">{approach.map((item, i) => <div className="flex items-center gap-4 border-b border-ink/15 py-4 text-sm text-ink/70" key={item}><span className="font-mono text-[10px] text-coral">0{i + 1}</span>{item}</div>)}</div></div></section>

    <section className="bg-mint px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><p className="section-label">06 / Experience</p><div className="mt-10 grid gap-8 border-t border-ink/15 pt-6 md:grid-cols-[.3fr_1fr_auto]"><div className="font-mono text-[10px] uppercase tracking-widest text-ink/50">Project-based</div><div><h3 className="font-display text-3xl">Full Stack Web Developer</h3><p className="mt-1 font-mono text-xs uppercase tracking-widest text-coral">Mazhai Boutique</p><p className="mt-5 max-w-xl text-sm leading-7 text-ink/65">Designed and developed a modern e-commerce website with a responsive interface, product browsing, shopping functionality and supporting full stack integrations.</p></div><div className="text-sm text-ink/50">Freelance / Project</div></div></div></section>

    <section id="contact" className="bg-ink px-5 py-20 text-paper lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><p className="section-label text-coral">07 / Contact</p><h2 className="mt-5 max-w-lg font-display text-5xl leading-[.95] tracking-[-.05em] md:text-7xl">Let's build something <span className="text-coral">great</span> together.</h2><p className="mt-7 max-w-md leading-7 text-paper/55">Have a project in mind? Share a few details and I will have a look. I am available by email, phone, WhatsApp, or LinkedIn.</p><div className="mt-10 flex flex-wrap gap-x-5 gap-y-4 text-sm text-paper/60"><a href="mailto:visvaeswaraiyajayakumar@gmail.com" aria-label="Email Visvaeswaraiya Jayakumar" className="flex items-center gap-2 hover:text-coral"><Mail size={16} /> Email</a><a href="tel:+918754731787" aria-label="Call Visvaeswaraiya Jayakumar" className="flex items-center gap-2 hover:text-coral"><Phone size={16} /> Phone</a><a href="https://wa.me/918754731787" target="_blank" rel="noreferrer" aria-label="Message on WhatsApp" className="flex items-center gap-2 hover:text-coral"><MessageCircle size={16} /> WhatsApp</a><a href="https://www.linkedin.com/in/visvaeswaraiya-jayakumar-405b0942b" target="_blank" rel="noreferrer" aria-label="Visvaeswaraiya Jayakumar on LinkedIn" className="flex items-center gap-2 hover:text-coral"><Linkedin size={16} /> LinkedIn</a></div></div></section>

    <footer className="bg-ink px-5 pb-8 text-paper lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 border-t border-paper/15 pt-8 md:flex-row md:items-end"><div><a href="#top" className="font-display text-2xl font-bold">VJ<span className="text-coral">.</span></a><p className="mt-2 text-xs text-paper/45">Visvaeswaraiya Jayakumar / Full Stack Web Developer</p></div><div className="flex flex-wrap gap-x-5 gap-y-3 text-xs text-paper/55">{nav.map(([label, id]) => <a className="hover:text-coral" href={`#${id}`} key={id}>{label}</a>)}</div><p className="text-[10px] uppercase tracking-widest text-paper/35">© {new Date().getFullYear()} Visvaeswaraiya Jayakumar</p></div></footer>

    {lightbox && <div role="dialog" aria-modal="true" aria-label="Project gallery" className="fixed inset-0 z-50 flex items-center justify-center bg-ink/90 p-5" onClick={() => setLightbox(null)}><div className="w-full max-w-4xl" onClick={(event) => event.stopPropagation()}><div className="mb-4 flex items-center justify-between text-paper"><div><p className="font-mono text-[10px] uppercase tracking-widest text-coral">Mazhai Boutique</p><h2 className="mt-1 font-display text-3xl">Project gallery</h2></div><button aria-label="Close gallery" onClick={() => setLightbox(null)} className="rounded-full border border-paper/30 p-2"><X size={20} /></button></div><div className="overflow-hidden rounded-[2px] border border-paper/20 bg-paper"><img src={mazhaiCollectionsUrl} alt="Mazhai Boutique collections page" className="max-h-[62vh] w-full object-contain" /></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{gallery.map((item) => <button key={item} onClick={() => setLightbox(item)} className="border border-paper/20 p-3 text-left text-[10px] uppercase tracking-wider text-paper/60 hover:border-coral hover:text-paper"><span className="mb-6 block h-14 bg-paper/10" />{item}</button>)}</div></div></div>}
    <section aria-label="Contact details" className="border-t border-ink/10 bg-paper px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center gap-x-6 gap-y-3 text-sm text-ink/65"><span className="font-display text-xl font-bold text-ink">Let's connect</span><a href="mailto:visvaeswaraiyajayakumar@gmail.com" aria-label="Email Visvaeswaraiya Jayakumar" className="flex items-center gap-2 hover:text-coral"><Mail size={17} className="text-coral" /> visvaeswaraiyajayakumar@gmail.com</a><a href="tel:+918754731787" aria-label="Call Visvaeswaraiya Jayakumar" className="flex items-center gap-2 hover:text-coral"><Phone size={17} className="text-coral" /> +91 87547 31787</a><a href="https://wa.me/918754731787" target="_blank" rel="noreferrer" aria-label="Message on WhatsApp" className="flex items-center gap-2 hover:text-coral"><MessageCircle size={17} className="text-coral" /> WhatsApp</a><a href="https://www.linkedin.com/in/visvaeswaraiya-jayakumar-405b0942b" target="_blank" rel="noreferrer" aria-label="Visvaesraiya Jayakumar on LinkedIn" className="flex items-center gap-2 hover:text-coral"><Linkedin size={17} className="text-coral" /> LinkedIn</a></div></section>
    <section aria-label="Project context" className="border-t border-ink/10 bg-paper px-5 py-8 lg:px-8"><div className="mx-auto grid max-w-7xl gap-4 text-sm text-ink/65 md:grid-cols-2"><p><strong className="text-ink">Education projects:</strong> college-level projects completed as part of my academic work.</p><p><strong className="text-ink">Mazhai Boutique:</strong> a real-time project demonstrating a live e-commerce experience.</p></div></section>
  </main>;
}
